image: registry.gitlab.com/gluttton/munkres-cpp


stages:
    - test


test_job:
    stage: test
    before_script:
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug ${BUILD_DIR}/..
        - make
    script:
        - ./test/hampel_test
        - gcovr -e '../test' -e 'test/googletest' -r ..
